AS	=	MASM
ASFLAGS	=	

PSHELL.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;

PSMAIN.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;

SSPROC.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;

SSLET.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;

SSDIR.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;

SSDEBU.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;

SSTYPE.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;

SSLOAD.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;

SSADRS.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;

SSFILE.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;

SSFORM.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;

INT21H.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;

DOSIO.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;

DOSWRT.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;

READWT.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;

READSEC.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;

DKFORM.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;

MACLIB.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;

CONSOLE.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;

LINKEND.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;

